name: Build the docker image for wayne

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: docker registry credentials
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: sonatribe
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run: npm install -g ember-cli tailwindcss
    - run: npm install
    - id: get_version
      uses: battila7/get-version-action@v2
    - run: echo ${{ steps.get_version.outputs.version }}

    - run: ember build production --env=production
      env:
        CI: true
        A_RECORD: highstreetly
        DASH_API: https://api.dashboard.highstreetly.link
        DASH_UI: https://dashboard.highstreetly.link
        OPS_API: https://api.ops.highstreetly.link
        OPS_UI: https://ops.highstreetly.link
        DOMAIN: highstreetly.link
        IDS: https://ids.highstreetly.link
        MAIN_API: https://api.highstreetly.link
        MAIN_UI: https://highstreetly.link
        NAMESPACE: highstreetly-link
        ORDERS_API: https://api.orders.highstreetly.link
        ORDERS_UI: https://orders.highstreetly.link
        TICKETS_API: https://api.shop.highstreetly.link
        TICKETS_UI: https://shop.highstreetly.link
        TLD: link
        WIDGET_API: https://api.widget.highstreetly.link
        VERSION: ${{ steps.get_version.outputs.version }}
        STRIPE_CLIENT_ID: ca_BZCgKyvK7Ywug3UOghG5VHADqYbNRTz9

    - name: Build the Docker image sonatribe/highstreet-operator-wayne
      run: docker build -t sonatribe/highstreet-operator-wayne:${{ steps.get_version.outputs.version }} .
    - name: push sonatribe/highstreet-operator-wayne
      run: docker push sonatribe/highstreet-operator-wayne:${{ steps.get_version.outputs.version }}

