name: Build the docker image for live

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: docker registry credentials
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: sonatribe
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run: npm install -g ember-cli tailwindcss
    - run: npm install
    - id: get_version
      uses: battila7/get-version-action@v2
    - run: echo ${{ steps.get_version.outputs.version }}

    - run: ember build production --env=production
      env:
        CI: true
        A_RECORD: highstreet
        DASH_API: https://api.operator.highstreet.ly
        DASH_UI: https://operator.highstreet.ly
        DOMAIN=: highstreet.ly
        IDS: https://ids.highstreet.ly
        MAIN_API: https://api.highstreet.ly
        MAIN_UI: https://highstreet.ly
        NAMESPACE: highstreet-ly
        ORDERS_API: https://api.orders.highstreet.ly
        ORDERS_UI: https://orders.highstreet.ly
        TICKETS_API: https://api.shop.highstreet.ly
        TICKETS_UI: https://shop.highstreet.ly
        TLD: ly
        WIDGET_API: https://api.widget.highstreet.ly
        VERSION: ${{ steps.get_version.outputs.version }}
        STRIPE_CLIENT_ID: ca_BZCgZcukzBPBndf075LUCSQccEEF9q24

    - name: Build the Docker image sonatribe/highstreet-operator-live
      run: docker build -t sonatribe/highstreet-operator-live:${{ steps.get_version.outputs.version }} .
    - name: push sonatribe/highstreet-operator-live
      run: docker push sonatribe/highstreet-operator-live:${{ steps.get_version.outputs.version }}


