name: Build and deploy operator.
on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g ember-cli tailwindcss
    - run: npm install
    - run: ember build
      env:
        CI: true
        A_RECORD: highstreet
        DASH_API: https://api.operator.highstreet.ly
        DASH_UI: https://operator.highstreet.ly
        DOMAIN=: highstreet.ly
        MAIN_API: https://api.highstreet.ly
        MAIN_UI: https://highstreet.ly
        NAMESPACE: highstreet-ly
        ORDERS_API: https://api.orders.highstreet.ly
        ORDERS_UI: https://orders.highstreet.ly
        TICKETS_API: https://api.shop.highstreet.ly
        TICKETS_UI: https://shop.highstreet.ly
        TLD: ly
        WIDGET_API: https://api.widget.highstreet.ly
        STRIPE_CLIENT_ID: ca_BZCgKyvK7Ywug3UOghG5VHADqYbNRTz9

